/*
 * generated by Xtext 2.15.0
 */
package org.edla.xtext.tptp


/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
class TptpRuntimeModule extends AbstractTptpRuntimeModule {
}
