/*
 * generated by Xtext 2.15.0
 */
package org.edla.xtext.tptp


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
class TptpStandaloneSetup extends TptpStandaloneSetupGenerated {

	def static void doSetup() {
		new TptpStandaloneSetup().createInjectorAndDoEMFRegistration()
	}
}
