/**
 * generated by Xtext 2.15.0
 */
package org.edla.xtext.tptp.validation;

import org.edla.xtext.tptp.validation.AbstractTptpValidator;

/**
 * This class contains custom validation rules.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#validation
 */
@SuppressWarnings("all")
public class TptpValidator extends AbstractTptpValidator {
}
