/**
 * generated by Xtext 2.15.0
 */
package org.edla.xtext.tptp;

import org.edla.xtext.tptp.AbstractTptpRuntimeModule;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
@SuppressWarnings("all")
public class TptpRuntimeModule extends AbstractTptpRuntimeModule {
}
