/**
 * generated by Xtext 2.15.0
 */
package org.edla.xtext.tptp.ide;

import org.edla.xtext.tptp.ide.AbstractTptpIdeModule;

/**
 * Use this class to register ide components.
 */
@SuppressWarnings("all")
public class TptpIdeModule extends AbstractTptpIdeModule {
}
