/**
 * generated by Xtext 2.15.0
 */
package org.edla.xtext.tptp.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import org.eclipse.xtext.util.Modules2;
import org.edla.xtext.tptp.TptpRuntimeModule;
import org.edla.xtext.tptp.TptpStandaloneSetup;
import org.edla.xtext.tptp.ide.TptpIdeModule;

/**
 * Initialization support for running Xtext languages as language servers.
 */
@SuppressWarnings("all")
public class TptpIdeSetup extends TptpStandaloneSetup {
  @Override
  public Injector createInjector() {
    TptpRuntimeModule _tptpRuntimeModule = new TptpRuntimeModule();
    TptpIdeModule _tptpIdeModule = new TptpIdeModule();
    return Guice.createInjector(Modules2.mixin(_tptpRuntimeModule, _tptpIdeModule));
  }
}
