/*
 * generated by Xtext 2.15.0
 */
package org.edla.xtext.tptp.ide

import com.google.inject.Guice
import org.eclipse.xtext.util.Modules2
import org.edla.xtext.tptp.TptpRuntimeModule
import org.edla.xtext.tptp.TptpStandaloneSetup

/**
 * Initialization support for running Xtext languages as language servers.
 */
class TptpIdeSetup extends TptpStandaloneSetup {

	override createInjector() {
		Guice.createInjector(Modules2.mixin(new TptpRuntimeModule, new TptpIdeModule))
	}
	
}
